### ISSUE TITLE
Domain/ConceptScheme landing page missing its child relationships

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/thesaurus#1]
The issue seems to be in app.py

    def relationships(self):
        """
        given a concept get all related,
        broader and narrower terms
        """
        relationships = []
        for c in [SKOS.broader, SKOS.related, SKOS.narrower, SKOS.member]:
            this_results = []
            for rel in graph.objects(subject=URIRef(self.concept), predicate=c):
                rel_label = get_preferred_label(rel, self.lang)
                this_results.append({'type': c.split('#')[1], 'uri': rel, 'pref_label': rel_label})
            sorted_results = sorted(this_results, key=lambda tup: tup['pref_label'])
            for sr in sorted_results:
                relationships.append(sr)
        return relationships

SKOS.member isn't in use in the data set. Domain/ConceptScheme membership is asserted via SKOS.hasTopConcept

I've already fixed the page listing, but this also needs to be applied to the API, from which it's missing.

**Comment by aaronhelton** [comment]
![xml-domain-view](https://user-images.githubusercontent.com/617997/39874988-5de8b34e-543d-11e8-8aff-bf77dd4eb16f.png)

**Comment by fiacre** [comment]
Fixed in 84b0b53
